# Generated by Django 4.2.5 on 2023-09-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadEDI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                (
                    "edi_file",
                    models.FileField(
                        upload_to="static/edi/%Y-%m-%d/", verbose_name="FILE EDI"
                    ),
                ),
                (
                    "upload_seq",
                    models.CharField(
                        choices=[
                            ("0", "Revise 0"),
                            ("1", "Revise 1"),
                            ("2", "Revise 2"),
                            ("3", "Revise 3"),
                            ("4", "Revise 4"),
                            ("5", "Revise 5"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Upload Seq.",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="Is Generated"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upload_by_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload By ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูล UploadFileEDI",
                "verbose_name_plural": "Upload File EDI",
                "db_table": "tbtUploadFileEDI",
            },
        ),
        migrations.CreateModel(
            name="RequestOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                (
                    "revise_level",
                    models.CharField(
                        choices=[
                            ("0", "Revise 0"),
                            ("1", "Revise 1"),
                            ("2", "Revise 2"),
                            ("3", "Revise 3"),
                            ("4", "Revise 4"),
                            ("5", "Revise 5"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Revise Level",
                    ),
                ),
                ("qty", models.FloatField(default="0.0", verbose_name="Qty.")),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Generate Purchase Request"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplier.book",
                        verbose_name="Book ID",
                    ),
                ),
                (
                    "created_by_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "edi_file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload_edi.uploadedi",
                        verbose_name="EDI File ID",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.product",
                        verbose_name="Product ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูล Request Order",
                "verbose_name_plural": "Request Order",
                "db_table": "tbtRequestOrder",
            },
        ),
    ]
