# Generated by Django 4.2.5 on 2023-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_edi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={'ordering': ['purchase_order_id', 'seq'], 'verbose_name': 'PO Detail', 'verbose_name_plural': 'Purchase Order Detail'},
        ),
        migrations.AlterField(
            model_name='approvepurchaseorder',
            name='purchase_request_status',
            field=models.CharField(choices=[('0', 'Draff'), ('1', 'In Process'), ('2', 'Success'), ('3', 'Failure')], default='0', max_length=1, verbose_name='Purchase Order Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('0', 'Draff'), ('1', 'In Process'), ('2', 'Success'), ('3', 'Failure')], default='0', max_length=1, verbose_name='Order Status'),
        ),
    ]
