# Generated by Django 4.2.5 on 2023-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_vcst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='FCPREFIX',
            field=models.CharField(blank=True, db_column='FCPREFIX', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='FCREFTYPE',
            field=models.CharField(blank=True, db_column='FCREFTYPE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='ppd3jFWR', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='coor',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='km8ZnAy5', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='EQHW7x5u', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='KmHx6dxo', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderh',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='SA8VX3GB', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderi',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='3EnxQPIJ', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='p2GDux7z', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sect',
            name='FCSKID',
            field=models.CharField(blank=True, db_column='FCSKID', default='HNXsFkPk', max_length=8, null=True),
        ),
    ]
