# Generated by Django 4.2.5 on 2023-09-28 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderConfirm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Invoice No."
                    ),
                ),
                (
                    "qty",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Qty."
                    ),
                ),
                (
                    "confirm_qty",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Confirm Qty."
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ข้อมูล Order Confirm",
                "verbose_name_plural": "Order Confirm",
                "db_table": "tbtOrderConfirm",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                (
                    "num_qty",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Num Qty."
                    ),
                ),
                (
                    "qty",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Qty."
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Price"
                    ),
                ),
                (
                    "vat",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Vat."
                    ),
                ),
                ("seq", models.IntegerField(default="0", verbose_name="Seq.")),
                (
                    "confirm_qty",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Confirm Qty."
                    ),
                ),
                (
                    "order_step",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("I", "In Process"),
                            ("P", "Paid"),
                            ("C", "Cancel"),
                            ("F", "Finish"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Order Step",
                    ),
                ),
                (
                    "is_confirm",
                    models.BooleanField(default=False, verbose_name="Is Confirm"),
                ),
                ("is_sync", models.BooleanField(default=False, verbose_name="Is Sync")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ข้อมูล Order Detail",
                "verbose_name_plural": "Order Detail",
                "db_table": "tbtOrderDetail",
            },
        ),
        migrations.CreateModel(
            name="OrderHead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Order Date")),
                (
                    "order_code",
                    models.CharField(max_length=150, unique=True, verbose_name="Code"),
                ),
                (
                    "order_no",
                    models.CharField(max_length=150, verbose_name="Order No."),
                ),
                (
                    "order_amount",
                    models.FloatField(
                        default="0.0", max_length=18, verbose_name="Order Amount"
                    ),
                ),
                (
                    "order_step",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("I", "In Process"),
                            ("P", "Paid"),
                            ("C", "Cancel"),
                            ("F", "Finish"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Order Step",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Invoice No."
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(null=True, verbose_name="Delivery Date"),
                ),
                (
                    "is_confirm",
                    models.BooleanField(default=False, verbose_name="Is Confirm"),
                ),
                ("is_sync", models.BooleanField(default=False, verbose_name="Is Sync")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ข้อมูล Order",
                "verbose_name_plural": "Order",
                "db_table": "tbtOrderHead",
            },
        ),
    ]
