# Generated by Django 4.2.5 on 2023-09-26 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='PRIMARY KEY')),
                ('order_skid', models.CharField(max_length=8, unique=True, verbose_name='Formula ID')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('order_code', models.CharField(max_length=150, unique=True, verbose_name='Code')),
                ('order_no', models.CharField(max_length=150, verbose_name='Order No.')),
                ('order_amount', models.FloatField(default='0.0', max_length=18, verbose_name='Order Amount')),
                ('order_step', models.CharField(choices=[('1', 'None'), ('P', 'Paid'), ('C', 'Cancel'), ('4', 'Finish')], default='1', max_length=1, verbose_name='Order Step')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Is Confirm')),
                ('is_sync', models.BooleanField(default=False, verbose_name='Is Sync')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.ordertype', verbose_name='Order Type ID')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='Supplier ID')),
            ],
            options={
                'verbose_name': 'ข้อมูล Order',
                'verbose_name_plural': 'Order',
                'db_table': 'tbtOrderHead',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='PRIMARY KEY')),
                ('order_skid', models.CharField(max_length=8, unique=True, verbose_name='Formula ID')),
                ('num_qty', models.FloatField(default='0.0', max_length=18, verbose_name='Num Qty.')),
                ('qty', models.FloatField(default='0.0', max_length=18, verbose_name='Qty.')),
                ('price', models.FloatField(default='0.0', max_length=18, verbose_name='Price')),
                ('vat', models.FloatField(default='0.0', max_length=18, verbose_name='Vat.')),
                ('seq', models.IntegerField(default='0', verbose_name='Seq.')),
                ('confirm_qty', models.FloatField(default='0.0', max_length=18, verbose_name='Confirm Qty.')),
                ('order_step', models.CharField(choices=[('1', 'None'), ('P', 'Paid'), ('C', 'Cancel'), ('4', 'Finish')], default='1', max_length=1, verbose_name='Order Step')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Is Confirm')),
                ('is_sync', models.BooleanField(default=False, verbose_name='Is Sync')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderhead', verbose_name='Order ID')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.product', verbose_name='Product ID')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.unit', verbose_name='Unit ID')),
            ],
            options={
                'verbose_name': 'ข้อมูล Order Detail',
                'verbose_name_plural': 'Order Detail',
                'db_table': 'tbtOrderDetail',
            },
        ),
    ]
