# Generated by Django 4.2.5 on 2023-09-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhead",
            name="order_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplier.ordertype",
                verbose_name="Order Type ID",
            ),
        ),
        migrations.AddField(
            model_name="orderhead",
            name="supplier_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplier.supplier",
                verbose_name="Supplier ID",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orderhead",
                verbose_name="Order ID",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="product_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.product",
                verbose_name="Product ID",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="unit_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplier.unit",
                verbose_name="Unit ID",
            ),
        ),
        migrations.AddField(
            model_name="orderconfirm",
            name="order_detail_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orderdetail",
                verbose_name="Order Detail ID",
            ),
        ),
        migrations.AddField(
            model_name="orderconfirm",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Confirm By ID",
            ),
        ),
    ]
